---
title: "dataTables"
author: "Sophie Castel"
date: "12/11/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SKEWS
```{r}
skewTab <- plotSkew(agEval = testag, output = "table")

setwd("/home/sophie/sophTools/files/tables")
print(xtable(skewTab), file="skewTab.txt", include.rownames = F, sanitize.text.function = function(x) x)
```

# BEST METHOD, g fixed, collapse across g
```{r}
f = "median"
cross_section = "p"
theFixed = "g"

# MAPE
crit = "MAPE"

## D1
btD1MAPE_p <-bestTable(d=1, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD1MAPE_p, "subheadings") <- names(btD1MAPE_p)
  
## D2
btD2MAPE_p <-bestTable(d=2, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD2MAPE_p, "subheadings") <- names(btD2MAPE_p)

## D3
btD3MAPE_g <-bestTable(d=3, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD3MAPE_p, "subheadings") <- names(btD3MAPE_p)

## D4
btD4MAPE_p <-bestTable(d=4, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD4MAPE_p, "subheadings") <- names(btD4MAPE_p)

## D5
btD5MAPE_p <-bestTable(d=5, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD5MAPE_p, "subheadings") <- names(btD5MAPE_p)

for (d in 1:5){
caption_MAPE[d] <- paste0("Sampling distribution of the ",f, " ",crit," values in dataset ",d,". Statistics are aggregated across $",theFixed,"$ and shown for each value of $",cross_section,"$.")
}

# NRMSD

crit = "NRMSD"

## D1
btD1NRMSD_p <-bestTable(d=1, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD1NRMSD_p, "subheadings") <- names(btD1NRMSD_p)
  
## D2
btD2NRMSD_p <-bestTable(d=2, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD2NRMSD_p, "subheadings") <- names(btD2NRMSD_p)

## D3
btD3NRMSD_p <-bestTable(d=3, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD3NRMSD_p, "subheadings") <- names(btD3NRMSD_p)

## D4
btD4NRMSD_p <-bestTable(d=4, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD4NRMSD_p, "subheadings") <- names(btD4NRMSD_p)

## D5
btD5NRMSD_p <-bestTable(d=5, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD5NRMSD_p, "subheadings") <- names(btD5NRMSD_p)

for (d in 1:5){
caption_NRMSD[d] <- paste0("Sampling distribution of the ",f, " ",crit," values in dataset ",d,". Statistics are aggregated across $",theFixed,"$ and shown for each value of $",cross_section,"$.")}
```

```{r}
setwd("/home/sophie/sophTools/files/tables/CSp/MAPE")

for(i in 1:5){
  fileConn <- file(paste("btD",i,"MAPE_p.txt",sep=""))
  
  writeLines(print(xtableList(eval(parse(text = paste("btD",i,"MAPE_p",sep=""))), caption = caption_MAPE[i]), 
        file = paste("btD",i,"MAPE_p.txt",sep=""),
        include.rownames = F,
        sanitize.text.function = function(x) x), fileConn)
  
  close(fileConn)
  }
  
setwd("/home/sophie/sophTools/files/tables/CSp/NRMSD")

for(i in 1:5){
  fileConn <- file(paste("btD",i,"NRMSD_p.txt",sep=""))
    writeLines(print(xtableList(eval(parse(text = paste("btD",i,"NRMSD_p",sep=""))), caption = caption_NRMSD[i]), 
        file = paste("btD",i,"NRMSD_p.txt",sep=""),
        include.rownames = F,
        sanitize.text.function = function(x) x), fileConn)
  
  close(fileConn)
  }

```

# BEST METHOD, p fixed, collapse across p
```{r}
f = "median"
cross_section = "g"
theFixed = "p"

# MAPE
crit = "MAPE"

## D1
btD1MAPE_g <-bestTable(d=1, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD1MAPE_g, "subheadings") <- names(btD1MAPE_g)
  
## D2
btD2MAPE_g <-bestTable(d=2, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD2MAPE_g, "subheadings") <- names(btD2MAPE_g)

## D3
btD3MAPE_g <-bestTable(d=3, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD3MAPE_g, "subheadings") <- names(btD3MAPE_g)

## D4
btD4MAPE_g <-bestTable(d=4, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD4MAPE_g, "subheadings") <- names(btD4MAPE_g)

## D5
btD5MAPE_g <-bestTable(d=5, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD5MAPE_g, "subheadings") <- names(btD5MAPE_g)

for (d in 1:5){
caption_MAPE[d] <- paste0("Sampling distribution of the ",f, " ",crit," values in dataset ",d,". Statistics are aggregated across $",theFixed,"$ and shown for each value of $",cross_section,"$.")
}


# NRMSD

crit = "NRMSD"

## D1
btD1NRMSD_g <-bestTable(d=1, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD1NRMSD_g, "subheadings") <- names(btD1NRMSD_g)
  
## D2
btD2NRMSD_g <-bestTable(d=2, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD2NRMSD_g, "subheadings") <- names(btD2NRMSD_g)

## D3
btD3NRMSD_g <-bestTable(d=3, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD3NRMSD_g, "subheadings") <- names(btD3NRMSD_g)

## D4
btD4NRMSD_g <-bestTable(d=4, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD4NRMSD_g, "subheadings") <- names(btD4NRMSD_g)

## D5
btD5NRMSD_g <-bestTable(d=5, agEval = testag, m=4:6, crit=crit, f = f, cross_section = cross_section, collapse = T)
attr(btD5NRMSD_g, "subheadings") <- names(btD5NRMSD_g)

for (d in 1:5){
caption_NRMSD[d] <- paste0("Sampling distribution of the ",f, " ",crit," values in dataset ",d,". Statistics are aggregated across $",theFixed,"$ and shown for each value of $",cross_section,"$.")}
```

```{r}
setwd("/home/sophie/sophTools/files/tables/CSg/MAPE")

for(i in 1:5){
  fileConn <- file(paste("btD",i,"MAPE_g.txt",sep=""))
  
  writeLines(print(xtableList(eval(parse(text = paste("btD",i,"MAPE_g",sep=""))), caption = caption_MAPE[i]), 
        file = paste("btD",i,"MAPE_g.txt",sep=""),
        include.rownames = F,
        sanitize.text.function = function(x) x), fileConn)
  
  close(fileConn)
}

setwd("/home/sophie/sophTools/files/tables/CSg/NRMSD")

for(i in 1:5){
  fileConn <- file(paste("btD",i,"NRMSD_g.txt",sep=""))
    writeLines(print(xtableList(eval(parse(text = paste("btD",i,"NRMSD_g",sep=""))), caption = caption_NRMSD[i]), 
        file = paste("btD",i,"NRMSD_g.txt",sep=""),
        include.rownames = F,
        sanitize.text.function = function(x) x), fileConn)
  
  close(fileConn)
  }

```

# GRADIENTS
```{r}
gg <- gradient(agEval = testag, crit = c("MAPE","NRMSE"), f = "median")
gg1 <- gg["gradients"][[1]][[1]][[2]] # criterion, method, dataset 
gg2 <- gg["gradients"][[1]][[2]][[2]] # criterion, method, dataset 
#gg3 <- gg["gradients"][[1]][[3]][[2]] # criterion, method, dataset 

# The maximum slope occurs at the following junction points:
gg1[which.max(gg1[,"slope"]),]
gg2[which.max(gg2[,"slope"]),]
#gg3[which.max(gg3[,"slope"]),]
```

# HEATMAP
```{r}
heatmap_grid <- heatmapGrid(gradientObject = gradient(agEval = testag, crit = "MSE"), agEval = testag, crit = "MSE", m = 1, d = 5, output = "matrix")

## BASE
stats::heatmap(abs(heatmap_grid), Rowv = NA, Colv = NA, revC = T, scale = "row")
library(RColorBrewer)
stats::heatmap(heatmap_grid, Rowv = NA, Colv = NA, revC = T, scale = "none", 
               labRow = gsub("0","",rownames(heatmap_grid),fixed=TRUE),
               labCol = gsub("0","",colnames(heatmap_grid),fixed=TRUE),
               xlab = "gap width", ylab = "proportion missing",
               col = colorRampPalette(c("firebrick1","blue"))(10000))

stats::heatmap(z_list[[1]][[1]][[1]], Rowv = NA, Colv = NA, revC = T, scale = "none", 
               labRow = gsub("0","",rownames(z_list[[1]][[1]][[1]]),fixed=TRUE),
               labCol = gsub("0","",colnames(z_list[[1]][[1]][[1]]),fixed=TRUE),
               xlab = "gap width", ylab = "proportion missing",
               col = colorRampPalette(c("firebrick1","firebrick"))(100000))

stats::heatmap(volcano, Rowv = NA, Colv = NA, revC = T, scale = "none", 
               labRow = gsub("0","",rownames(volcano),fixed=TRUE),
               labCol = gsub("0","",colnames(volcano),fixed=TRUE),
               xlab = "gap width", ylab = "proportion missing",
               col = colorRampPalette(c("black","red"))(1000000))


library(reshape2)
rownames(heatmap_grid) <- LETTERS[1:nrow(heatmap_grid)]
colnames(heatmap_grid) <- as.character(1:ncol(heatmap_grid))
  
## GGPLOT
h <- ggplot(data = data.frame(melt(heatmap_grid)), aes(x = Var2, y = Var1, fill = value)) + geom_tile()

```

