---
title: "High Resolution, by Dataset, HWI"
author: "Sophie Castel"
date: "2/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# test interpolation at very high resolution

#INITIALIZATION
```{r}
gap_vec <- seq(1,30, by = 2)
prop_vec <- seq(0.10,0.30, length.out=20)
K = 100
```

#SIMULATE DATA
```{r}
OriginalData <- load_obj("/home/sophie/sophTools/files/new_2/testOriginalData.rda")
```

#GAPIFY             
```{r}
set.seed(23)

GappyData <- list()

for(d in 1:length(OriginalData)){
  GappyData[[d]] <- simulateGaps(data = as.numeric(OriginalData[[d]]), prop_vec = prop_vec, gap_vec = gap_vec, K = K)
}
names(GappyData) <- names(OriginalData)

# dimension (d, p, g, k) 
```

# Check to see how many observations were removed; and if somewhat linear
```{r}
# Create plots
p=20
actual.gaps <- numeric()
expected.gaps <- numeric()

for(g in 1:length(GappyData[[1]][[1]])){
    actual.gaps[g] <- sum(is.na(GappyData[[1]][[p]][[g]][[1]]))
    expected.gaps[g] <- g
  }
names(actual.gaps) <- paste0("p",round(prop_vec[p],2),", g",gap_vec)
plot <- ggplot() + geom_line(aes(x = 1:length(gap_vec), y = actual.gaps)) + labs(x = "expected gaps", y = "actual gaps", title= paste0("mean = ",round(mean(actual.gaps),2),", expected = ", round(prop_vec[p]*1000),2)) + theme_minimal()

setwd("/home/sophie/sophTools/files/highRes/actualGaps")
png(paste0("p",p,".png"))
plot
dev.off()

# Get dataframe of results (actual and expected gaps)
mean.actual <- numeric()

for(p in 1:length(prop_vec)){
  actual.gaps <- numeric()
  for(g in 1:length(gap_vec)){
    actual.gaps[g] <- sum(is.na(GappyData[[1]][[p]][[g]][[2]]))
  }
  mean.actual[p] <- round(mean(actual.gaps),2)
}

result <- data.frame(expected = round(prop_vec*1000), actual = mean.actual, diff = mean.actual-round(prop_vec*1000))
setwd("/home/sophie/sophTools/files/highRes/actualGaps")
save(result, file = "result.rda")

setwd("/home/sophie/sophTools/files/highRes/actualGaps")
png("result.png")
plot(result$actual, type = "l", main = "Mean Actual Gaps", ylab = "Actual", xlab= "Expected")
dev.off()
```

# Split Data
```{r}
GappyData.hr <- load_obj("/home/sophie/sophTools/files/highRes/GappyData.hr.rda")
split = 20
splitData.hr <- splitData(GappyData.hr, split = split)
```

#INTERPOLATION
```{r IntData, cache = TRUE}
set.seed(23)
methods <- c(18)

# D1
for(n in 1:split){
    splitIntData <- parInterpolate(gappyTS = splitData.hr[[1]][[n]], methods = 18, numCores = 20)
    filename <- paste0("1_IntData.hr","_",letters[n],".rda")
    setwd(paste0("/home/sophie/sophTools/files/highRes/IntData.hr/D1"))
    save(splitIntData, file = filename)
    print(n)
    gc()
}

# D2
for(n in 1:split){
    splitIntData <- parInterpolate(gappyTS = splitData.hr[[2]][[n]], methods = 18, numCores = 25)
    filename <- paste0("2_IntData.hr","_",letters[n],".rda")
    setwd(paste0("/home/sophie/sophTools/files/highRes/IntData.hr/D2"))
    save(splitIntData, file = filename)
    print(n)
    gc()
}
# Note did not do split = 20 (time constraint)

# D3
for(n in 1:split){
    splitIntData <- parInterpolate(gappyTS = splitData.hr[[3]][[n]], methods = 18, numCores = 20)
    filename <- paste0("3_IntData.hr","_",letters[n],".rda")
    setwd(paste0("/home/sophie/sophTools/files/highRes/IntData.hr/D3"))
    save(splitIntData, file = filename)
    print(n)
    gc()
}

# D4
for(n in 1:split){
    splitIntData <- parInterpolate(gappyTS = splitData.hr[[4]][[n]], methods = 18, numCores = 20)
    filename <- paste0("4_IntData.hr","_",letters[n],".rda")
    setwd(paste0("/home/sophie/sophTools/files/highRes/IntData.hr/D4"))
    save(splitIntData, file = filename)
    print(n)
    gc()
}

# D5
for(n in 1:split){
    splitIntData <- parInterpolate(gappyTS = splitData.hr[[5]][[n]], methods = 18, numCores = 20)
    filename <- paste0("5_IntData.hr","_",letters[n],".rda")
    setwd(paste0("/home/sophie/sophTools/files/highRes/IntData.hr/D5"))
    save(splitIntData, file = filename)
    print(n)
    gc()
}
```

# STITCH DATA
```{r}
for(n in 20:20){
    splitIntData <- parInterpolate(gappyTS = splitData.hr[[2]][[n]], methods = 18, numCores = 25)
    filename <- paste0("2_IntData.hr","_",letters[n],".rda")
    setwd(paste0("/home/sophie/sophTools/files/highRes/IntData.hr/D2"))
    save(splitIntData, file = filename)
    print(n)
    gc()
}

IntData.hr.1 <- stitchData("/home/sophie/sophTools/files/highRes/IntData.hr/D1")
IntData.hr.2 <- stitchData("/home/sophie/sophTools/files/highRes/IntData.hr/D2")
IntData.hr.3 <- stitchData("/home/sophie/sophTools/files/highRes/IntData.hr/D3")
IntData.hr.4 <- stitchData("/home/sophie/sophTools/files/highRes/IntData.hr/D4")
IntData.hr.5 <- stitchData("/home/sophie/sophTools/files/highRes/IntData.hr/D5")

IntData.hr <- list(D1 = IntData.hr.1, D2 = IntData.hr.2, D3 = IntData.hr.3, D4 = IntData.hr.4, D5 = IntData.hr.5)
```

# PERFORMANCE MATRIX
```{r}
OriginalData.hr <- load_obj("/home/sophie/sophTools/files/new_2/testOriginalData.rda")
GappyData.hr <- load_obj("/home/sophie/sophTools/files/highRes/GappyData.hr.rda")

pMats.hr <- performance(OriginalData=OriginalData.hr, IntData=IntData.hr, GappyData = GappyData.hr)
ag.hr <- agEvaluate(pmats = pMats.hr)
setwd("/home/sophie/sophTools/files/highRes")
save(pMats.hr, file = "pMats.hr.rda")
save(ag.hr, file = "ag.hr.rda")
```

```{r}
#D1hm <- heatmapGrid(agEval = testag, crit = "NRMSD", m = "HWI", d = 1, type = "z")
#D2hm <- heatmapGrid(agEval = testag, crit = "NRMSD", m = "HWI", d = 2, type = "z")[[1]]
#D3hm <- heatmapGrid(agEval = testag, crit = "NRMSD", m = "HWI", d = 3, type = "z")[[1]]
#D4hm <- heatmapGrid(agEval = testag, crit = "NRMSD", m = "HWI", d = 4, type = "z")[[1]]
#D5hm <- heatmapGrid(agEval = testag, crit = "NRMSD", m = "HWI", d = 5, type = "z")[[1]]
# NOTE WE CANNOT USE THE HEATMAPGRID FUNCTION BECAUSE I COULDN'T FIGURE OUT HOW TO GET PLOTS SIDE BY SIDE.
# WENT WITH A GGPLOT INSTEAD.
ag.hr <- load_obj("/home/sophie/sophTools/files/highRes/ag.hr.rda")

z_list <- compileMatrix(ag.hr)[["median"]]

crit = "NRMSD"
m = "HWI"

plott <- list()
for(d in 1:5){
          rownames(z_list[[crit]][[m]][[d]]) <- gsub("p","",rownames(z_list[[crit]][[m]][[d]]), fixed = TRUE)
          colnames(z_list[[crit]][[m]][[d]]) <- gsub("g","",colnames(z_list[[crit]][[m]][[d]]), fixed = TRUE)

          
          plott[[d]] <- melt(z_list[[crit]][[m]][[d]])
          colnames(plott[[d]]) <- c("p","g", "value")
}
          
rng = range(c(plott[[1]]$value, plott[[2]]$value ,plott[[3]]$value, plott[[4]]$value, plott[[5]]$value))
col = c("#F9E0AA","#F7C65B","#FAAF08","#FA812F","#FA4032","#F92111")


D1 <- ggplot(plott[[1]], aes(as.numeric(p), as.numeric(g), fill = value)) + geom_tile() + 
      scale_fill_gradientn(colours = col, values = c(0,1),
                           limits = rng) +
  
  #scale_x_discrete(limits = c(0,0.30), breaks = c(0,0.05,0.10,0.15,0.2,0.25,0.3)) + 
  #scale_y_discrete(limits = c(0,30), breaks = c(0,5,10,15,20,25,30)) + 
            
        labs(x = "proportion missing", y = "gap width", fill = crit, title = "D1") + 
          theme_minimal() + 
  
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 12))

D2 <- ggplot(plott[[2]], aes(as.numeric(p), as.numeric(g), fill = value)) + geom_tile() + 
      scale_fill_gradientn(colours = col, values = c(0,1),
                           limits = rng) +
            
        labs(x = "proportion missing", y = "gap width", fill = crit, title = "D2") + 
          theme_minimal() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 12))

D3 <- ggplot(plott[[3]], aes(as.numeric(p), as.numeric(g), fill = value)) + geom_tile() + 
      scale_fill_gradientn(colours = col, values = c(0,1),
                           limits = rng) +
  
        labs(x = "proportion missing", y = "gap width", fill = crit, title = "D3") + 
          theme_minimal() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 12))

D4 <- ggplot(plott[[4]], aes(as.numeric(p), as.numeric(g), fill = value)) + geom_tile() + 
      scale_fill_gradientn(colours = col, values = c(0,1),
                           limits = rng) +
  
        labs(x = "proportion missing", y = "gap width", fill = crit, title = "D4") + 
          theme_minimal() + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 12))

D5 <- ggplot(plott[[5]], aes(as.numeric(p), as.numeric(g), fill = value)) + geom_tile() + 
      scale_fill_gradientn(colours = col, values = c(0,1),
                           limits = rng) +
            
        labs(x = "proportion missing", y = "gap width", fill = crit, title = "D5") + 
          theme_minimal() + 
  
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 12))
          
    # get legend
    g_legend<-function(a.gplot){
      tmp <- ggplot_gtable(ggplot_build(a.gplot))
      leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
      legend <- tmp$grobs[[leg]]
      return(legend)}
    
    # make dummy plot to retrieve legend
    dumPlot <- ggplot(plott[[5]], aes(as.factor(p), as.factor(g), fill = value)) + geom_tile() + 
      scale_fill_gradientn(colours = col, values = c(0,1),
                           limits = rng) +
      theme(legend.position = "bottom") + 
      labs(fill = crit)
  
    myLegend<-g_legend(dumPlot)
    
plotWindow <- grid.arrange(D1,D2,D3,D4,D5, ncol = 5, bottom = "proportion missing", left = "gap width")

setwd("/home/sophie/sophTools/files/highRes")
png(paste0(crit,"_Heatmap_hr.png"), width = 1136, height = 328)
plotWindow <- grid.arrange(plotWindow, myLegend, heights = c(10,2))
dev.off()
```

# Side-by-side metrics (Heatmaps)
```{r}
ag.hr <- load_obj("/home/sophie/sophTools/files/highRes/ag.hr.rda")

setwd("/home/sophie/sophTools/files/highRes")
png("Heatmaps_hr.png", width = 1100, height = 1100)
multiHeatmap(crit = c("NRMSD","MAPE","MRE","RMSS"), m = "KAF", agEval = new.ag)
dev.off()

```

# SURFACE PLOTS
```{r}
ag.hr <- load_obj("/home/sophie/sophTools/files/highRes/ag.hr.rda")

# Create legend
greyList <- c("#EAECEE", "#D5D8DC","#ABB2B9","#808B96", "#566573", "#2C3E50")
highlight = "HWI"
highlight_colour =  "#EE5C42"

# get z_list
z_list <- compileMatrix(agEval=ag.hr)[["median"]]

method_list_names <- names(z_list[[1]])
M <- length(method_list_names)

greyListMatch <- greyList[1:M]
names(greyListMatch) <- method_list_names
greyListMatch[[highlight]] <- highlight_colour
  
manualLegend <- data.frame(color = as.character(greyListMatch), 
                           nameSurface = method_list_names, 
                           x = rep(0,M), 
                           y = seq(0.20,0.80,length.out = M), 
                           textcol = as.character(greyListMatch),
                           stringsAsFactors = FALSE)

theLegend.hr <- plot_ly(data = manualLegend, showlegend = F) %>%
  
  add_markers(x = manualLegend$x,
              y = manualLegend$y, 
              size = 50, 
              name = manualLegend$nameSurface,
              color = I(manualLegend$color)) %>%
  
  add_text(x = manualLegend$x + 0.03,
           y = manualLegend$y,
           text = manualLegend$nameSurface,
           color = I(manualLegend$textcol),
           textposition = "right") %>% 
  
              layout(xaxis = list(title = "", 
                                  showgrid = F, 
                                  showticklabels = F,
                                  zeroline = F,
                                  range = c(-0.15,0.3)), 
                     yaxis = list(title = "", 
                                  showgrid = F, 
                                  showticklabels = F,
                                  zeroline = F,
                                  range = c(0,1.05)))
```

### Generate surface plots
```{r}
ps.hr <- plotSurface(agEval = ag.hr, m = "HWI", layer_type = "method", d = 1:5, highlight = "HWI", crit = "MAPE", f = "median", scale = "mint")

titleList <- list()

for(i in 1:length(ps.hr[[1]])){
      titleList[[i]] <- list(
        text = paste("Dataset ",i,sep=""),
        xref = "paper",
        yref = "paper",
        yanchor = "bottom",
        xanchor = "center",
        align = "center",
        x = 0.5,
        y = 0.75,
        showarrow = FALSE
      )
    }

pp1NRMSD.hr <- ps.hr[[1]][[1]] %>% layout(annotations = titleList[[1]])# criterion, dataset
pp2NRMSD.hr <- ps.hr[[1]][[2]] %>% layout(annotations = titleList[[2]])# criterion, dataset
pp3NRMSD.hr <- ps.hr[[1]][[3]] %>% layout(annotations = titleList[[3]])# criterion, dataset
pp4NRMSD.hr <- ps.hr[[1]][[4]] %>% layout(annotations = titleList[[4]])# criterion, dataset
pp5NRMSD.hr <- ps.hr[[1]][[5]] %>% layout(annotations = titleList[[5]])# criterion, dataset

sub1  <- subplot(pp1NRMSD.hr,pp2NRMSD.hr,pp3NRMSD.hr,pp4NRMSD.hr,pp5NRMSD.hr,theLegend.hr, nrows = 3) %>%
  
            layout(title = names(ps.hr)[1],
             
             scene = list(domain=list(x=c(0,1/2),  y=c(2/3,1)), 
                          aspectmode = 'manual', 
                          aspectratio=list(x=1,y=1,z=0.5),
                          camera = list(eye=list(x=1.65,y=-1.15,z=0.30))),
             
             scene2 = list(domain=list(x=c(1/2,1), y=c(2/3,1)), 
                           aspectmode = 'manual', 
                           aspectratio=list(x=1,y=1,z=0.5),
                           camera = list(eye=list(x=1.65,y=-1.15,z=0.30))),
             
             scene3 = list(domain=list(x=c(0,1/2), y=c(1/3,2/3)), 
                           aspectmode = 'manual', 
                           aspectratio=list(x=1,y=1,z=0.5),
                           camera = list(eye=list(x=1.65,y=-1.15,z=0.30))),
             
             scene4 = list(domain=list(x=c(1/2,1), y=c(1/3,2/3)), 
                           aspectmode = 'manual', 
                           aspectratio=list(x=1,y=1,z=0.5),
                           camera = list(eye=list(x=1.65,y=-1.15,z=0.30))),
             
             scene5 = list(domain=list(x=c(0,1/2), y=c(0,1/3)), 
                           aspectmode = 'manual', 
                           aspectratio=list(x=1,y=1,z=0.5),
                           camera = list(eye=list(x=1.65,y=-1.15,z=0.30))),
             
             scene6 = list(domain=list(x=c(1/2,1), y=c(0,1/3)))
             )
```

These are ugly ^ :) 



